services:

  server:                    # The name of the service, can be anything
    image: example-app    # Declares which image to use
    build:
      context: . # The context will pick this directory as the "build context"
      dockerfile: dev.Dockerfile # This will simply tell which dockerfile to read
    volumes:
      - ./:/usr/src/example-app # The path can be relative, so ./ is enough to say "the same location as the docker-compose.yml"
    ports:
      - 3003:3003
    container_name: example-app # This will name the container todo-backend
    depends_on:
      - postgres

  postgres:
    image: postgres
    ports:
     - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./postgres_data:/data/db
    container_name: example-app-database


volumes:
  postgres_data: