POST http://localhost:3001/api/blogs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNjaGF0dG8xIiwiaWQiOjEsImlhdCI6MTcwMTIyMDIxNn0.sr43bDv3G4HHhuEb0YBFIdtfBM2pin6icjKonKVnAaY
Content-Type: application/json

{
  "author": "Sumon Chattopadhyay",
  "url": "redcap-software-engineering",
  "title": "Software Engineering Capabilities of the REDCap team"
}