POST http://localhost:3001/api/blogs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImR6c2h1NDlAZ21haWwuY29tIiwiaWQiOjEsImlhdCI6MTcwMTQ3NDc1NX0.M_mwg5jewMUXzgb8ETpdAeyWh7x2lw7iHug1-J1YSUE
Content-Type: application/json

{
  "author": "Sumon Chattopadhyay",
  "url": "project-management",
  "title": "A Dummy's Guide to Project Management",
  "likes": 5,
  "year": 2023
}