POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImR6c2h1NDlAZ21haWwuY29tIiwiaWQiOjEsImlhdCI6MTcwMjEwNDkwM30.9_gaAZ0zAm45rMD2lIAaQo55IuA5BGY6G4UZFceB_as

{
  "author": "Laurenz Albe",
  "url": "postgres-sequence-gap",
  "title": "Gaps in sequences in PostGreSQL"
}