PUT http://localhost:3001/api/readinglists/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RpbmdAdGVzdC5jb20iLCJpZCI6MywiaWF0IjoxNzAyMDc3NjA1fQ.m12xM3n8XQFJFbRjsss8N_uPtDdW4UFQ-F8SvKdLJnE
Content-Type: application/json

{
  "read": true
}